services:
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: trainify-client
  #   container_name: trainify-client
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db

  db:
    image: postgres
    container_name: trainify-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
